kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-server-blocks
  namespace: ed84ea-test
immutable: false
data:
  server_block.conf: |-
    server {
          listen 8081;
          listen [::]:8081;
          server_name klamm-app-ed84ea-test.apps.silver.devops.gov.bc.ca;
          error_page 401 403 = @login_required;

          # anyone with IDIR identity can access this
          location / {
            auth_request /auth/;
            auth_request_set $auth_status $upstream_status;
            proxy_set_header Host klamm-app-ed84ea-test.apps.silver.devops.gov.bc.ca;
            proxy_set_header X-Original-URI $request_uri;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_read_timeout 300s;
            proxy_connect_timeout 75s;
            proxy_pass http://klamm-app/;
          }

          location /auth/ {
            internal;
            proxy_pass_request_body off;
            proxy_set_header Content-Length "";
            proxy_set_header Host $http_host;
            proxy_set_header X-Original-URI $request_uri;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Authorization $http_authorization;
            proxy_pass_header Authorization;
            proxy_pass http://sso-client-node/;
          }

          location /sso-login {
            proxy_set_header Host $host;
            proxy_set_header X-Original-URI $request_uri;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_pass http://sso-client-node/authn;
          }

          location /sso {
            proxy_set_header Host $host;
            proxy_set_header X-Original-URI $request_uri;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_pass http://sso-client-node/authn/callback;
          }

          location @login_required {
            return 302 https://klamm-app-ed84ea-test.apps.silver.devops.gov.bc.ca/sso-login?relay=$request_uri;
          }

        }
